name: Refresh 冰芽川四系乃 CDN

on:
  push:
    branches: [ main ]
    paths:
      - 'lua/冰芽川四系乃.lua'
      - '资源/*.png'
      - '资源/*.mp3'
  release:
    types: [published]

jobs:
  refresh-cdn:
    runs-on: ubuntu-latest
    steps:
      - name: Purge main script
        run: |
          echo "Refreshing 冰芽川四系乃.lua CDN cache..."
          curl -s -o /dev/null -w "Status: %{http_code}\n" \
            -X POST "https://purge.jsdelivr.net/gh/ThirteenSpices/ThirteenSpicesYoshino/main/lua/冰芽川四系乃.lua"
          
      - name: Purge resource files
        run: |
          echo "Refreshing resource files CDN cache..."
          curl -s -o /dev/null -w "Status: %{http_code}\n" \
            -X POST "https://purge.jsdelivr.net/gh/ThirteenSpices/ThirteenSpicesYoshino/main/资源/"
          
      - name: Verify CDN update
        run: |
          echo "Waiting 10 秒之前 for CDN propagation..."
          sleep 10
          
          curl -s -o /dev/null -w "Main script status: %{http_code}\n" \
            "https://cdn.jsdelivr.net/gh/ThirteenSpices/ThirteenSpicesYoshino@main/lua/冰芽川四系乃.lua"
